service: twilio-lambda-functions
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::972126823319:role/lambdacarddate
  region: us-east-2
  memorySize: 256
  timeout: 10
  environment:
    twilioAccountSid: ${env:TWILIO_ACCOUNT_SID}
    twilioAuthToken: ${env:TWILIO_AUTH_TOKEN}

functions:
  SendSms:
    handler: handler.sendSms
    events:
      - http:
          path: api/sendSms
          method: post
          integration: lambda
          cors: true
  ReceiveSms:
    handler: rec_webhook.receiveSms
    events:
      - http:
          path: api/receiveSms
          method: post
          integration: lambda
          cors: true
