service: twilio-lambda-functions
frameworkVersion: ">=1.1.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::972126823319:role/lambdacarddate
  region: us-east-2
  memorySize: 256
  timeout: 10
  environment:
    # Replace these environment variables with your Twilio and Google values
    TWILIO_ACCOUNT_SID: AC81ea16ec867a1fd9a781b51a20d8f7c6
    TWILIO_AUTH_TOKEN: 4ee58b3faa8b0c267f20d51cbf809a83
    TWILIO_PHONE_NUMBER: +13143103033


functions:
  SendSms:
    handler: handler.sendSms
    events:
      - http:
          path: api/sendSms
          method: post
          integration: lambda
          cors: true
  ReceiveSms:
    handler: rec_webhook.receiveSms
    events:
      - http:
          path: api/receiveSms
          method: post
          integration: lambda
          cors: true
